name: Publish and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release SystemHub
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: SystemHubSetup.exe
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
